blog/urls.py
from . import views


from django.urls import path

urlpattern = [
    path('edit_profile/', views.edit_profile, name="edit_profile"),
#     path('post_create/', views.post_create, name="post_create"),
#     path('blog/<int:id>/<slug:slug>/',  views.post_detail, name="post_detail"),
 ]

blog_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from blog import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),
    path('success/', views.success, name="success"),
    path('privacy/', views.privacy, name="privacy"),
    path('terms/', views.terms, name="terms"),
    path('blog/', views.post_list, name="post_list"),
    path('', views.index_view, name="index_view"),
    path('<int:id>/post_edit/', views.post_edit, name="post_edit"),
    path('<int:id>/post_delete/', views.post_delete, name="post_delete"),
    path('<int:id>/favourite_post/', views.favourite_post, name="favourite_post"),
    path('blog/<int:id>/<slug:slug>/',  views.post_detail, name="post_detail"),
    path('blog/post_create/', views.post_create, name="post_create"),
    path('login/', views.user_login, name="user_login"),
    path('logout/', views.user_logout, name="user_logout"),
    path('register/', views.register, name="register"),
    path('edit_profile/', views.edit_profile, name="edit_profile"),
    path('favourites/', views.post_favourite_list, name="post_favourite_list"),
    # Password Reset path
    # path('password_reset/', auth_views.PasswordChangeView.as_view(), name="password_reset"),
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view() , name="password_reset_done"),
    # path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    # path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),

    # path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
	# path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
	
	# path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
	# path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
	# path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
	# path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('', include('django.contrib.auth.urls')),
    path('oauth/', include('social_django.urls', namespace="social")),  
    path('like/', views.like_post, name="like_post"),
]









if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.text import slugify
from django.core.exceptions import ObjectDoesNotExist
# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status="published")




class Post(models.Model):
    objects = models.Manager()
    published = PublishedManager()


    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=120)
    author = models.ForeignKey(User, related_name='blog_posts',  on_delete=models.CASCADE)
    body = models.TextField()
    likes = models.ManyToManyField(User, related_name='likes', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    restrict_comment = models.BooleanField(default=False)
    favourite = models.ManyToManyField(User, related_name='favourite', blank=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.title

    def total_likes(self):
        return self.likes.count()


    def get_absolute_url(self):
        return reverse("post_detail", args=[self.id, self.slug])
@receiver(pre_save, sender=Post)
def pre_save_slug(sender, **kwargs):
    slug = slugify(kwargs['instance'].title)
    kwargs['instance'].slug = slug


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dob = models.DateField(null=True, blank=True)
    photo = models.ImageField(null=True, blank=True)


    def __str__(self):
        return "Profile of user {}".format(self.user.username)



class Images(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/', blank=True, null=True)


    def __str__(self):
        return str(self.post.id)
        # return self.post.title + " Image "

# class Profile(models.Model):
#     template_name = 'edit_profile.html'

#     def def get_context_data(self, **kwargs):
#         context = super(Profile, self).get_context_data(**kwargs)
#         context['event_list'] = Event.objects.all()
#         if self.request.user.is_authenticated():
#             try:
#                 my_location = self.request.user.userlocation
#             except ObjectDoesNotExist:

#             else:
#                 primt("The location is{}".format(my_location))
#         return context



class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete= models.CASCADE)
    user = models.ForeignKey(User, on_delete= models.CASCADE)
    reply = models.ForeignKey('Comment', null=True, related_name='replies', on_delete= models.CASCADE)
    content = models.TextField(max_length=160)
    timestamp = models.DateTimeField(auto_now_add=True)



    def __str__(self):
        return '{}-{}'.format(self.post.title, str(self.user.username))

blog/views.py
from django.conf import settings
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from datetime import datetime
from django.urls import reverse
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, Http404
from .models import Post, Profile, Images, Comment
from .forms import *
from django.contrib.auth import authenticate, login, logout
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template.loader import render_to_string
from django.forms import modelformset_factory
from django.contrib import messages
from django.core.mail import send_mail
# Create your views here.

def index_view(request):
    return render(request, 'blog/index.html')

def about(request):
    return render(request, 'blog/about.html')

def contact(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            # first_name = form.cleaned_data['first_name']
            # last_name = form.cleaned_data['last_name']
            name = form.cleaned_data['name']
            subject = form.cleaned_data['subject']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, email, ['oamenjamiu@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('success')
    return render(request, "blog/contact.html", {'form': form})

def success(request):
    return render(request, "blog/success.html")

def privacy(request):
    return render(request, 'blog/privacy.html')

def terms(request):
    return render(request, 'blog/terms.html')

def post_list(request):
    post_list = Post.published.all()
    query = request.GET.get('q')
    if query:
        post_list = Post.published.filter(
        Q(title__icontains=query)|
        Q(author__username=query)|
        Q(body__icontains=query)           
        )
    paginator = Paginator(post_list, 6)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)


    if page is None:
        start_index = 0
        end_index = 4
    else:
        (start_index, end_index) = proper_pagination(posts, index=4)


    page_range = list(paginator.page_range)[start_index:end_index]
    # [1,2,3,4,5,6,7][0:7]



    context = {
        'posts': posts,
        'page_range': page_range,
    }
    return render(request, 'blog/post_list.html', context)

def proper_pagination(posts, index):
    start_index = 0
    end_index = 4
    if posts.number > index:
        start_index = posts.number - index
        end_index = start_index + end_index
    return (start_index, end_index)


def post_detail(request, id, slug):
    post = get_object_or_404(Post, id=id, slug=slug)
    comments = Comment.objects.filter(post=post, reply=None).order_by('-id')
    is_liked = False
    is_favourite = False
    if post.likes.filter(id=request.user.id).exists():
        is_liked = True

    if post.favourite.filter(id=request.user.id).exists():
        is_favourite = True


    if request.method =='POST':
        comment_form = CommentForm(request.POST or None)
        if comment_form.is_valid():
            content = request.POST.get('content')
            reply_id = request.POST.get('comment_id')
            comment_qs = None
            if reply_id:
                comment_qs = Comment.objects.get(id=reply_id)
            comment = Comment.objects.create(post=post, user=request.user, content=content, reply=comment_qs)
            comment.save()
            # return HttpResponseRedirect(post.get_absolute_url())


    else:
        comment_form = CommentForm()



    context = {
        'post': post,
        'is_liked': is_liked,
        'is_favourite': is_favourite,
        'total_likes': post.total_likes(),
        'comments': comments,
        'comment_form': comment_form,
    }
    if request.is_ajax():
        html = render_to_string('blog/comments.html', context, request=request)        
        return JsonResponse({'form': html})

    return render(request, 'blog/post_detail.html', context)


def post_favourite_list(request):
    user = request.user
    favourite_posts = user.favourite.all()
    context = {
        'favourite_posts': favourite_posts,
    }
    return render(request, 'blog/post_favourite_list.html', context)




def favourite_post(request, id):
    post = get_object_or_404(Post, id=id)
    if post.favourite.filter(id=request.user.id).exists():
        post.favourite.remove(request.user)
        
    else:
        post.favourite.add(request.user)
    return HttpResponseRedirect(post.get_absolute_url())

            


def like_post(request):
    # post = get_object_or_404(Post, id=request.POST.get('post_id'))
    post = get_object_or_404(Post, id=request.POST.get('id'))
    is_liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        is_liked = False
    else:
        post.likes.add(request.user)
        is_liked = True
    context = {
        'post': post,
        'is_liked': is_liked,
        'total_likes': post.total_likes(),
    }
    if request.is_ajax():
        html = render_to_string('blog/like_section.html', context, request=request)
        return JsonResponse({'form': html})
    return HttpResponseRedirect(post.get_absolute_url())




def post_create(request):
    
    ImageFormset = modelformset_factory(Images, fields=('image',), extra=4)
    form = PostCreateForm(request.POST)
    formset = ImageFormset(request.POST or None, request.FILES or None)
    if request.method == 'POST':
        
        
        
        if form.is_valid() and formset.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()


            for f in formset:
                try:
                    photo = Images(post=post, image=f.cleaned_data['image'])
                    photo.save()
                    
                except Exception as e:
                    break
            messages.success(request, "Post has been successfully created")
            return redirect('post_list')



        else:
            form = PostCreateForm()
            formset = ImageFormset(queryset=Images.objects.none())
    context = {
        'form': form,
        'formset': formset,
    }
    return render(request, 'blog/post_create.html', context)


def post_edit(request, id): 
    post = get_object_or_404(Post, id=id)
    ImageFormset = modelformset_factory(Images, fields=('image',), extra=4, max_num=4)
    if request.method == "POST":
        form = PostEditForm(request.POST or None, instance=post)
        formset = ImageFormset(request.POST or None, request.FILES or None)
        if form.is_valid() and formset.is_valid():
            form.save() 
            print(formset.cleaned_data)
            data = Images.objects.filter(post=post)

            for index, f in enumerate(formset):
                if f.cleaned_data:
                    if f.cleaned_data['id'] is None:
                        photo = Images(post=post, image=f.cleaned_data.get('image'))
                        photo.save()
                    elif f.cleaned_data['image'] is False:
                        photo = Images.objects.get(id=request.POST.get('form-' + str(index) + '-id'))
                        photo.delete()
                    else:
                         photo = Images(post=post, image=f.cleaned_data.get('image'))
                         d = Images.objects.get(id=data[index].id)
                         d.image = photo.image
                         d.save()
            messages.success(request, "{} has been successfully updated!".format(post.title))
            return HttpResponseRedirect(post.get_absolute_url())
    else:
        form = PostEditForm(instance=post)
        formset = ImageFormset(queryset=Images.objects.filter(post=post))
    context = {
    'form': form,
    'post': post,
    'formset': formset,
    }
    return render(request, 'blog/post_edit.html', context)    



def user_login(request):


    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse('post_list'))
                else:
                    return HttpResponse("User is not active")
            else:
                return render(request, 'blog/non_user.html')
                # return HttpResponse("We are Sorry To inform You That, Your details are not Registered")
    else:

        form = UserLoginForm()

    context = {
        'form': form,
    }
    return render(request, 'blog/login.html', context)



def user_logout(request):
    logout(request)
    return redirect('post_list')


def register(request):


    if request.method == 'POST':
        form = UserRegistrationForm(request.POST or None)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()
            Profile.objects.create(user=new_user)
            return redirect('login')

    else:
        form = UserRegistrationForm()
    context = {
        'form': form,
    }
    return render(request, 'registration/register.html', context)






@login_required
def edit_profile(request):


    
    if request.method == 'POST':

templates/blog/alerts.html
<div class="messages">
    {% if messages %}
        {% for message in messages %}
            <p class="alert alert-{{ message.tags }}">
                {{ message }}
            </p>
        {% endfor %}
    {% endif %}
</div>

templates/blog/background_image.html
<!-- {% load static %}

<!DOCTYPE html>
<html>
    <head>
        <style>
            body {
                background: url("{% static 'images/index1.jpg' %}") no-repeat center center fixed;
                -webkit-background-size: cover;
                -moz-background-size: cover;
                -o-background-size: cover;
                background-size: cover;
            }
        </style>
    </head>
</html>

 <html>
    <head>
        <style>
            body {
                background-color: rgba(78, 170, 165, 0.966);
            }
        </style>
    </head>
</html> -->

templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <title>{% block title %}Jay's blog{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
     integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
        integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

            <!-- to Enable dropdown -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
        
        <!-- enabling ends here -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
</head>

<body>
    
    
    {% include 'blog/background_image.html' %}
    {% include 'blog/navbar.html' %}
    <div class="container-fluid text-capitalize" class="font-weight-bold">
        
        {% block content %}
        {% endblock %}
        
    </div>
    {% include 'blog/footer.html' %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script type="text/javascript">
     $(document).ready(function (event) {

        $('#delete').click(function(){
            return confirm("Are you sure you want to delete this post?");
        });


        $('.reply-btn').click(function(){
            $(this).parent().parent().next('.replied-comments').fadeToggle()
        });


        $(function(){
            setTimeout(function(){
                $('.alert').slideUp(2000);
            }, 5000);
        });


        $(document).ready(function (event) {
            $(document).on('click', '#like', function (event) {
                event.preventDefault();
                var pk = $(this).attr('value');
                $.ajax({
                    type: 'POST',
                    url: '{% url "like_post" %}',
                    data: { 'id': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}' },
                    dataType: 'json',
                    success: function (response) {
                        $('#like-section').html(response['form'])
                        console.log($['#like-section'].html(response['form']));
                    },
                    error: function (rs, e) {
                        console.log(rs.responseText);
                    },
                });

            });

        });
     });


     $(document).on('submit', '.comment-form', function(event){
         event.preventDefault();
         console.log($(this).serialize());
         $.ajax({
             type: 'POST',
             url: $(this).attr('action'),
             data: $(this).serialize(),
             dataType: 'json',
             success: function(response) {
                 $('.main-comment-section').html(response['form']);
                 $('textarea').val('');
                 $('.reply-btn').click(function() {
                     $(this).parent().parent().next('.replied-comments').fadeToggle();
                 });
             },
             error: function(rs, e) {
                 console.log(rs.responseText);
             },
         });
     });




      $(document).on('submit', '.reply-form', function (event) {
            event.preventDefault();
            console.log($(this).serialize());
            $.ajax({
                type: 'POST',
                url: $(this).attr('action'),
                data: $(this).serialize(),
                dataType: 'json',
                success: function (response) {
                    $('.main-comment-section').html(response['form']);
                    $('textarea').val('');
                    $('.reply-btn').click(function () {
                        $(this).parent().parent().next('.replied-comments').fadeToggle();
                    });
                },
                error: function (rs, e) {
                    console.log(rs.responseText);
                },
            });
        });













</script>



</body>

</html>


{{ p.get_absolute_url }}

templates/blog/edit_profile.html
{% extends 'blog/base.html' %}
{% block title %}Edit Profile | {{ block.super }}{% endblock %}
{% block content %}
</div>
<br>
<br>
<br>
<br><br>
<br>
<br>
<div class="container" id="form-wrapper" style="max-width:500px;margin:auto;">
    <form action="." method="post" enctype="multipart/form-data">
        <strong>
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        </strong>
        <input type="submit" value="Save Changes" class="btn btn-outline-success">
    </form>
</div>
<br>
<br>
<br>
<br><br>
<br>
<br>
{% endblock %}

templates/blog/login.html
{% extends 'blog/base.html' %}
{% block content %}
</div>
<br>
<br>
<br>
<br><br>
<br>
<br>
<div class="container" id="form-wrapper" style="max-width:500px;margin:auto;">
    <form method="post">
        <strong>
        {% csrf_token %}
        {{ form.as_p }}
        </strong>
        <input type="submit" value="Login" class="btn btn-outline-success">
        <br>
        <br>
        <small>
            <a href="{% url 'register' %}">
                <button type="button" name="button" class="btn btn-outline-primary">Register</button>
            </a> |     
            <a href="{% url 'password_reset' %}">
                <button type="button" name="button" class="btn btn-outline-danger">Forgotten Your Password?</button>
            </a>
        </small>
        <br>
        <br>
        
        <strong>  OR  </strong><br>
        <b>Login With Social Account:</b><br><br>
        <a href="{% url 'social:begin' 'github' %}">
            <button type="button" name="button" class="btn btn-primary"><i class="fab fa-linkedin-in">Linked in</i></button>
        </a>  |   
        <a href="{% url 'social:begin' 'google-oauth2' %}">
            <button type="button" name="button" class="btn btn-danger"><i class="fab fa-google">oogle+</i></button>
        </a>  |  
        <a href="{% url 'social:begin' 'facebook' %}">
            <button type="button" name="button" class="btn btn-danger"><i class="fab fa-facebook">acebook</i></button>
        </a>
    </form>
</div>
</div>
<br>
<br>
<br>
<br><br>
<br>
<br>
{% endblock %}

templates/blog/non_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>You are Not Registered With Jay's Blog, Click <a href="{% url 'register' %}">Here</a> To register And get Your Free Account Today!</h1>
</body>
</html>

templates/blog/post_create.html
{% extends 'blog/base.html' %}
{% block content %}
</div>
<br>
<br>
<br>
<br>
<br>
<div class="container-fluid" id="form-wrapper" style="max-width:500px;margin:auto;">
    <form method="post" enctype="multipart/form-data">
        <strong>
        {% csrf_token  %}
        {{ form.as_p }}
        {{ formset.as_table }}
        </strong>
        <input type="submit" value="Create" class="btn btn-outline-success">
    </form>
    
</div>
</div>
<br>
<br>
<br>
<br><br>
<br>
<br>
{% endblock %}

templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block title %}{{ post.title }} | {{ block.super }}{% endblock %}

{% block content %}

{% include 'blog/alerts.html' %}
<br>
<br>
<br>
<br>
<br>
<div class="container" >
  <strong>
  <h1>{{ post.title }}</h1>
  <b><p>Post created by: {{ post.author }}</p></b>
  <hr>
  <p>{{ post.body }}</p>

  <div class="row gallery">
    {% for p in post.images_set.all %}
      <div class="col-md-3">
        <img src="{{ p.image.url }}" alt="Image Not Found" class="img-thumbnail">
      </div>
    {% endfor %}
  </div>


<div id="like-section">
  {% include 'blog/like_section.html' %}
</div>


{% if request.user.is_authenticated %}
<div id="favourite-section">
  {% if is_favourite %}
  <a href="{% url 'favourite_post' id=post.id %}">
      <i class="fas fa-heart fa-lg"></i>
  </a>
  {% else %}
  <a href="{% url 'favourite_post' id=post.id %}">
    <i class="far fa-heart fa-lg"></i>
  </a>
  {% endif %}
</div>
{% endif %}



{% if post.author == request.user %}


<div class="section-1" style="float:right;">
  <a href="{% url 'post_edit' id=post.id %}">
    <button type="button" class="btn btn-outline-success">Edit</button>
  </a>
  <a href="{% url 'post_delete' id=post.id %}" id="delete">
    <button type="button" class="btn btn-danger">Delete</button>
  </a>
</div>
{% endif %}


<br><br>
<hr>

{% if not post.restrict_comment %}
<div class="main-comment-section">
  {% include 'blog/comments.html' %}
</div>
{% endif %}

</strong>







</div>
<br>
<br>
<br>
{% endblock %}

templates/blog/post_favourite_list.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
{% for p in favourite_posts %}

    <div class="container">
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="{% static 'images/default-avatar.png' %}" alt="Card image cap">
            Title: {{ p.title }}<br>
            Author: {{ p.author }}<br>
            Created On: {{ p.created }}<br>
            <div class="container">
                <a href="{{ p.get_absolute_url }}" class="btn btn-outline-danger">Read More</a>
            </div>
        </div>
        <br>
    </div>
    {% empty %}
    <div class="container-fluid">
        <h3>No Favourite Post(s) Found."</h3>
    </div>

    {% endfor %}


</div>
{% endblock %}

templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %}Welcome to {{ block.super }}{% endblock %}


{% block content %}

{% include 'blog/alerts.html' %}
<div class="container">
<div class="row">
    {% for p in posts %}
    <div class="col-md-4">
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="{% static 'images/default-avatar.png' %}" alt="Card image cap">
            Title: {{ p.title }}<br>
            Author: {{ p.author }}<br>
            Created On: {{ p.created }}<br>
        <div class="container">
            <!-- <div class="col-lg-12"> -->
        <a href="{{ p.get_absolute_url }}" class="btn btn-outline-danger">Read More</a>
        <!-- </div> -->
        </div>
    </div>
        <br>
    </div>
    {% empty %}
        <div class="container-fluid">
            <h3>No Post Found having search query "{{ request.GET.q }}"</h3>
        </div>

    {% endfor %}
</div>


<div class="container">
<ul class="pagination">
    {% if posts.has_previous %}
        <li class="page-item">
            <a href="?page={{ posts.previous_page_number }}" class="page-link">&laquo;</a>
        </li>
    {% endif %}


    {% for p in page_range %}
        {% if posts.number == p %}
            <li class="page-item active">
                <a href="?page={{ p }}" class="page-link">{{ p }}</a>
            </li>
        {% else %}
            <li class="page-item">
                <a href="?page={{ p }}" class="page-link">{{ p }}</a>
            </li>
        {% endif %}
    {% endfor %}

    {% if posts.has_next %}
    <li class="page-item">
        <a href="?page={{ posts.next_page_number }}" class="page-link">&raquo;</a>
    </li>
    {% endif %}
</div>

</ul>
</div>
{% endblock %}